# Generated by Django 4.2.7 on 2023-11-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='son', to='models_guide3.person')),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppartner', to='models_guide3.person')),
                ('siblings', models.ManyToManyField(blank=True, to='models_guide3.person')),
            ],
        ),
    ]
