# Generated by Django 4.2.7 on 2023-11-17 19:54

from django.db import migrations
import models_guide4.models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='even_int',
            field=models_guide4.models.EvenInteger(),
        ),
    ]
