# Generated by Django 4.2.7 on 2023-11-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_guide', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_guide2.dean')),
                ('diploma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models_guide2.diploma')),
                ('someOtherAppModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_guide.user')),
                ('teachers', models.ManyToManyField(to='models_guide2.teacher')),
            ],
        ),
    ]
