# Generated by Django 4.2.7 on 2023-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide2', '0002_dean_int_value_dean_str_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dean',
            name='str_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
