# Generated by Django 4.2.7 on 2023-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
