# Generated by Django 4.2.7 on 2023-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0002_alter_user_first_name_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='M', max_length=1, verbose_name='Pol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Prezime'),
        ),
    ]
