# Generated by Django 4.2.7 on 2023-11-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('O', 'Other'), ('F', 'Female'), ('M', 'Male')], default='M', max_length=1, verbose_name='Pol'),
        ),
    ]
