# Generated by Django 4.2.7 on 2023-11-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Pol'),
        ),
    ]
