# Generated by Django 4.2.7 on 2023-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide', '0008_alter_user_email_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Pol'),
        ),
    ]
